### ISSUE TITLE
Nouvelles questions pour la FAQ

### ISSUE THREAD

**Issue by fionnh** [IGNF/evolution-apigeoportail#10]
Gilles,

Voici les questions sur l’API qui me sont posées (ou auxquelles je pense qu’il serait utile qu’on puisse répondre) et qui pourraient éventuellement alimentées une FAQ :

L'évolution indiquée nous obligera-t-elle à redéployer nos applis ? 

Peut-on rester sur la configuration actuelle sans être impacté ?

Est-ce qu’il faudra tout réécrire ou il y aura des « passerelles » permettant de passer de la V2 à la V3 ?

Est-ce qu’on peut prévoir la migration en 2017 ?

Est-ce que l’API V2 cessera de fonctionner ?

Comment sommes-nous impactés ? Quels temps cela prendra-t-il de passer à la nouvelle version ?

Pour mon utilisation, dois-je utiliser le cas 1, 2 ou 3 ? Comment savoir ?

Proposez-vous des réunions et des échanges entre techniciens, notamment avec nos prestataires qui développent ?

**Comment by gcebelieu** [comment]
La plupart des questions est intégrée (avec réponses) ici :

http://ignf.github.io/evolution-apigeoportail/faq.html
