### ISSUE TITLE
Mettre la FAQ dans l'arborescence principale

### ISSUE THREAD

**Issue by fionnh** [IGNF/evolution-apigeoportail#12]
La FAQ est écrite (et est pas mal) mais n'a pas été poussée dans l'arbo principale. Du coup elle est assez inaccessible.

Peut-on la publier à droite de "Bibliothèque d'accès / Extension OL3 / Extension Leaflet / SDK" ?

**Comment by gcebelieu** [comment]
Une entrée "?" a été rajoutée dans le bandeau principal à droite des quatre autres comme demandé.
