### ISSUE TITLE
Manque une page FAQ (suggestions de questions dans le ticket)

### ISSUE THREAD

**Issue by fionnh** [IGNF/evolution-apigeoportail#9]
Voici un certain nombre de questions en vrac, inspirées de questions réelles ou supposée, pour vous aider à démarrer sur l’API.
- Quand arriveront les éléments promis ?
- Comment en serai-je averti ?
- J’ai fait développer mon site par un prestataire avec qui je n’ai plus de relations, comment savoir si j’utilise ou non l’API Géoportail ?
- Ce changement va-t-il m’obliger à changer de clé API ?
- Avez-vous un système qui permet d’afficher une carte en se passant complètement de votre API ?
- Finalement, recommandez-vous Leaflet ou Openlayers 3 ? 
- A qui m’adresser pour de l’aide ?
- Connaissez-vous des sociétés de service informatique à même de m’aider ?
- Pourquoi n’assurez-vous rien après mi-2017 ?
- Que se passera-t-i en juin 2017 si je ne fais pas évoluer le code de mon site ?
- Que devient votre API 3D ? Que recommandez-vous pour de la 3D ?
- Pourquoi oubliez-vous le « S » majuscule à JavaScript une fois sur deux ? 
- Quelle est la licence des extensions proposées ?
- Pendant combien de temps allez-vous assurer une maintenance ?
- Que se passera-t-il quand Leafle/OL évoluera ?

**Comment by gcebelieu** [comment]
Elle est ici :

http://ignf.github.io/evolution-apigeoportail/faq.html
